# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LycXMEuY07AY02Qbkdsq043VhTTrSZTA
"""

import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="cache-library",
    version="0.0.1",
    author="KevinN",
    author_email="h180800@gmail.com",
    description="Chacing library for python",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/kevinkevin1987/cache-library",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=2.7',
)